--- #YAML:1.0
name:                iThenticate-API-Request
version:             0.06
abstract:            create request objects for the iThenticate::API
license:             ~
author:              
    - Fred Moyer<fred@(?:redhotpenguin|turnitin).com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    RPC::XML:                      1.36
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
